theme: jekyll-theme-cayman
<!DOCTYPE html><html><head>
  <title>1° JCC Italia | L'innovativa coppa U18</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Product+Sans|Titillium+Web|Bungee" rel="stylesheet" type="text/css">
  <link rel="stylesheet" type="text/css" href="main.css" id="theme">
  <link rel="shortcut icon" href="images/favicon.ico">
</head>

<body>
<header class="container-fluid">
  <div class="row">
    <div class="col-xs-4 col-sm-2">
      <a href="https://jccitalia.github.io"><img src="images/08.png"></a>
    </div>
    <nav class="col-xs-8 col-sm-10 text-right">
      <a href="https://jccitalia.github.io/contatti"><p>Contatti</p></a>
      <a href="https://jccitalia.github.io/faq"><p>FAQ</p></a>
      <a href="https://lichess.org/team/jcc-italia" target="_blank"><p>Forum</p></a>
    </nav>
  </div>
</header>

<section class="jumbotron" id="J01">
  <div class="container">
    <div class="row text-center">
      <h2>1<sup>a</sup> Junior Chess Cup Italia</h2>
      <h3>L'innovativa coppa U18</h3>
      <a href="https://chat.whatsapp.com/3ZRdt0IlgPn6XoSKkdjppN"><button class="btn btn-lg" id="jccArena">Iscriviti</button></a>
      <!-- <a href="https://lichess.org/tournament/sjB9xQSU"><button class="btn btn-lg" id="jccArena">Accedi al torneo</button></a> -->
    </div>
  </div>
</section>

<section class="container" id="SL01">
  <div id="powrIframeLoader">­<style> .powrLoaded iframe { visibility: hidden; } </style></div><script src="//www.powr.io/powr.js?external-type=html"></script>
  <div class="powr-multi-slider hidden-xs powrLoaded" id="87be8989_1518027780"><iframe src="https://www.powr.io/plugins/multi-slider/cached_view?load=async&amp;index=0&amp;unique_label=87be8989_1518027780&amp;powr_token=jccitalia.github.io&amp;user_label=&amp;demo_mode=false&amp;external_type=html&amp;template_powr_token=&amp;color=rgb(51%2C%2051%2C%2051)&amp;backgroundColor=rgb(255%2C%20255%2C%20255)&amp;fontFamily=MyWebFont%2C%20%22Titillium%20Web%22" powrindex="0" width="100%" height="362px" frameborder="0" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" style="height: 362px; visibility: visible;"></iframe></div>
</section>

<section class="container">
  <div class="row" id="IB01">
    <div class="tab">
      <button class="tablinks" onclick="openCity(event, 'Torneo')">Torneo</button>
      <button class="tablinks active" id="defaultOpen" onclick="openCity(event, 'Gioca')">Gioca</button>
      <button class="tablinks" onclick="openCity(event, 'Impara')">Impara</button>
      <button class="tablinks" onclick="openCity(event, 'Altro')">Altro</button>
    </div>

    <div id="Torneo" class="tabcontent" style="display: none;">
      <figure class="col-xs-6 col-sm-4 col-md-2">
        <a href="https://jccitalia.github.io/countdown"><img src="https://jccitalia.github.io/images/02.png"></a>
        <p align="center">Countdown</p>
      </figure>
      <figure class="col-xs-6 col-sm-4 col-md-2">
        <a href="https://jccitalia.github.io/iscriviti"><img src="https://jccitalia.github.io/images/03.png"></a>
        <p align="center">Iscriviti</p>
      </figure>
      <figure class="col-xs-6 col-sm-4 col-md-2">
        <a href="https://jccitalia.github.io/classifica"><img src="https://jccitalia.github.io/images/04.png"></a>
        <p align="center">Classifica</p>
      </figure>
    </div>

    <div id="Gioca" class="tabcontent" style="display: block;">
      <figure class="col-xs-6 col-sm-4 col-md-2">
        <a href="https://lichess.org/?user=Vale18349276#friend" target="_blank"><img src="https://jccitalia.github.io/images/01.png"></a>
        <p align="center">Sfidami!</p>
      </figure>
      <figure class="col-xs-6 col-sm-4 col-md-2 hidden-xs hidden-sm">
        <a href="https://jccitalia.github.io/gioca"><img src="https://jccitalia.github.io/images/12.png"></a>
        <p align="center">Gioca</p>
      </figure>
      <figure class="col-xs-6 col-sm-4 col-md-2 visible-xs visible-sm">
        <a href="https://play.google.com/store/apps/details?id=org.lichess.mobileapp" target="_blank"><img src="https://jccitalia.github.io/images/12.png"></a>
        <p align="center">Gioca</p>
      </figure>
      <figure class="col-xs-6 col-sm-4 col-md-2">
        <a href="https://jccitalia.github.io/partiteasquadre"><img src="https://jccitalia.github.io/images/05.png"></a>
        <p align="center">Partite a squadre</p>
      </figure>
      <figure class="col-xs-6 col-sm-4 col-md-2">
        <a href="https://jccitalia.github.io/partecipanti"><img src="https://jccitalia.github.io/images/16.png"></a>
        <p align="center">Membri online</p>
      </figure>
    </div>

    <div id="Impara" class="tabcontent" style="display: none;">
      <figure class="col-xs-6 col-sm-4 col-md-2">
        <a href="https://jccitalia.github.io/lapartitazza"><img src="https://jccitalia.github.io/images/06.png"></a>
        <p align="center">La Partitazza</p>
      </figure>
      <figure class="col-xs-6 col-sm-4 col-md-2 hidden-xs hidden-sm">
        <a href="https://jccitalia.github.io/impara"><img src="https://jccitalia.github.io/images/13.png"></a>
        <p align="center">Impara a giocare</p>
      </figure>
      <figure class="col-xs-6 col-sm-4 col-md-2 visible-xs visible-sm">
        <a href="https://lichess.org/learn" target="_blank"><img src="https://jccitalia.github.io/images/13.png"></a>
        <p align="center">Impara a giocare</p>
      </figure>
      <figure class="col-xs-6 col-sm-4 col-md-2">
        <a href="https://lichess.org/tv" target="_blank"><img src="https://jccitalia.github.io/images/14.png"></a>
        <p align="center">Lichess TV</p>
      </figure>
      <figure class="col-xs-6 col-sm-4 col-md-2 hidden-xs hidden-sm">
        <a href="https://jccitalia.github.io/tattica"><img src="https://jccitalia.github.io/images/15.png"></a>
        <p align="center">Quesiti di tattica</p>
      </figure>
      <figure class="col-xs-6 col-sm-4 col-md-2 visible-xs visible-sm">
        <a href="https://lichess.org/training" target="_blank"><img src="https://jccitalia.github.io/images/15.png"></a>
        <p align="center">Quesiti di tattica</p>
      </figure>
    </div>

    <div id="Altro" class="tabcontent" style="display: none;">
      <figure class="col-xs-6 col-sm-4 col-md-2">
        <a href="https://jccitalia.github.io/contatti"><img src="https://jccitalia.github.io/images/09.png"></a>
        <p align="center">Contatti</p>
      </figure>
      <figure class="col-xs-6 col-sm-4 col-md-2">
        <a href="https://jccitalia.github.io/faq"><img src="https://jccitalia.github.io/images/10.png"></a>
        <p align="center">FAQ</p>
      </figure>
      <figure class="col-xs-6 col-sm-4 col-md-2">
        <a href="https://lichess.org/team/jcc-italia" target="_blank"><img src="https://jccitalia.github.io/images/11.png"></a>
        <p align="center">Forum</p>
      </figure>
    </div>

    <script>
      function openCity(evt, cityName) {
        // Declare all variables
        var i, tabcontent, tablinks;

        // Get all elements with class="tabcontent" and hide them
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }

        // Get all elements with class="tablinks" and remove the class "active"
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }

        // Show the current tab, and add an "active" class to the button that opened the tab
        document.getElementById(cityName).style.display = "block";
        evt.currentTarget.className += " active";
        }
    </script>

    <script>
      // Get the element with id="defaultOpen" and click on it
      document.getElementById("defaultOpen").click();
    </script>

  </div>
</section>

<footer class="container">
  <div class="row">
    <p class="col-sm-4">© 2018 1<sup>a</sup> JCC Italia</p>
    <div class="col-sm-8">
      <a href="http://www.hitwebcounter.com" target="_blank">
      <img src="http://hitwebcounter.com/counter/counter.php?page=6921044&amp;style=0010&amp;nbdigits=5&amp;type=page&amp;initCount=1500" title="Free track counters" alt="Free track counters" border="0">
      </a>
    </div>
    <!-- nascosto
    <script type="text/javascript">var pos = "bottomright"; var ico = "22_22";</script>
    <script type="text/javascript" src="https://www.iolecal.it/blog/posts400/post459/tornaSu.js"></script>
    -->
  </div>
</footer>



</body></html>
